### ISSUE TITLE
Floating windows don't move between the displays in window management mode

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#184]
If I have tiling turned on and enter window management mode, I can move a window from one display to another with just the arrow keys. However in floating mode, the window stops at the edge of the display, and I can't move the window to another display. I think this may be related to https://github.com/pop-os/shell/issues/183 and stopping windows from being movable off the edge of a display.

**Comment by mmstick** [comment]
Is there a certain kind of window that does this? I haven't been able to replicate it so far.

**Comment by leviport** [comment]
It seemed like all of them, but the ones I specifically remember trying were Firefox, gnome-terminal, and Nautilus. It might also be worth mentioning that I had the external display configured above the laptop's internal display, not to either side. I didn't test it to the sides yet.

**Comment by leviport** [comment]
Can confirm that this is related to displays being arranged vertically. Since the window stops at the top bar, I suspect that code preventing windows from going under the top bar is the cause. Windows move fine across displays as long as they don't have to cross the top bar.

**Comment by WatchMkr** [comment]
Fixed!

**Comment by leviport** [comment]
I'm still getting windows refusing to traverse the top bar to a secondary display arranged above my primary display. Is this intended behavior?
