### ISSUE TITLE
Focusing on notification exits full-screen

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#185]
This started happening after (37135dc48ae73970efa156260cd2fc9aa5097a5f). Intended behaviour is that you remain in full-screen, unless you actually click on the notification to launch the app that triggered it.

**Comment by mmstick** [comment]
What kind of notification?

**Comment by nicolae-stroncea** [comment]
Any notification from Gnome(email notification, notification from the terminal etc)

**Comment by mmstick** [comment]
I think this is fixed now

**Comment by mmstick** [comment]
Re-open if this is still an issue

**Comment by nicolae-stroncea** [comment]
Still occurs to me, on most recent commit e34bad62b1973048278ee3f205e44c90eea37193.

To reproduce:
1. Open terminal, do `sleep 3`.
2. Open nautilus make full screen, wait for notification from terminal.
3. Focusing on notification forces nautilus out of full-screen

**Comment by nicolae-stroncea** [comment]
Pulled again, seems to work now
