### ISSUE TITLE
Closed Applications Appear Running in the GNOME Dash and Activities View (Can't open app)

### ISSUE THREAD

**Issue by ankushdas9** [pop-os/shell#220]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not sure about that.

**Issue/Bug Description:**

When I enable the "Tile Windows" feature and then switch workspaces while closing some apps (not evening running in the background), the dock (or the favorites menu) still shows them active.

As you can see in the image here: https://imgur.com/QPIQZbq

Even though Firefox and the file manager has been closed (not even in the background, I repeat). The icon still shows up in the menu as **active** for some reason.

This only happens when I have the tile windows feature enabled and try to switch workspaces.

**Steps to reproduce (if you know):**

1. Enabled **Tile Windows.**
2. Open any app in the first workspace
3. Open any app in the second workspace.
4. Close an app and make sure it's not running in the background.
5. Check your dock/menu.

**Expected behavior:**

It should not show that dot thing under the app icon (which indicates that the app is still active).

**Other Notes:**

Feel free to edit the **title** of this issue, I wasn't quite sure how to put it.

**Comment by jannikbuhr** [comment]
This is likely related to #224

**Comment by mmstick** [comment]
Fixed by 16b4c33a8542969f19471b13b90764575a45ccf9

**Comment by esrocker1** [comment]
The issue is still persisting,more over after the update even Pop Shop has stopped opening.

**Comment by jannikbuhr** [comment]
I noticed the issue persisting as well, but disabling and re-enabling the pop-shell extension seems to have fixed it. Does that work for you?

**Comment by esrocker1** [comment]
Yeah!1 that seems do the trick. Thanks,any recommendations for the pop shop not opening???

**Comment by algom** [comment]
Issue still persist in Pop OS 20.04 (Fresh install) up to date. 
How to replicate: Open Firefox, open a new Firefox window, close both windows from Dash (Quit both windows) the application seems to continue running and no other window can be open unless launched from the Terminal. 
Disable/re-enable Pop-shell extension does not do anything. Can only be "rescued" by Alt+F2, r.
The same happens with Chrome.

Moreover, doing a right click on the icon (Firefox or Chrome) freezes my computer for a several seconds, mouse can be moved but no commands can be executed with the keyboard. Afterwards it recovers and Alt+F2, r, puts everything back to normal.

**Comment by leviport** [comment]
I can confirm. While I'm not seeing the "Close all" option on right click by default (must be a dash-to-dock addition), I can reproduce by opening 2 Nautilus windows and closing both at once with Ctrl+Q

**Comment by rybber78** [comment]
Confirmed here with Firefox and 2-3 windows open. Can ALT+CTRL+F3 (TTY3), login, start HTOP and there will be 1-2 processes using 100% CPU. If I kill the process(es), and return to TTY1 it's back to normal and dot under Firefox in dock is gone.

**Comment by nicolae-stroncea** [comment]
Can confirm with Virtualbox. To reproduce just open VirtualBox, then close it.

**Comment by dunestorm333** [comment]
If apps become zombies in your taskbar, one way to clear them is to press ALT + F2 and enter 'r'. This will reload GNOME, this doesn't stop the issue from reoccurring but saves you from having to logout when it does happen.

**Comment by jmmaranan** [comment]
Anyone want to re-test this in the latest pop-shell release? :)

**Comment by jannikbuhr** [comment]
I am currently testing and haven't managed to end up with a ghost application, yet. Looks good so far :)

**Comment by rthery** [comment]
Can't reproduce it either! Thanks @jmmaranan, finally can use Dash to Dock again!

**Comment by dunestorm333** [comment]
Yeah I can no longer reproduce the problem in VirtualBox. I tried to open both VBox Manage and a VM itself, both didn't leave ghost icons whereas previously they would! Thanks everyone for fixing it :)

**Comment by tunix** [comment]
I started to face this issue in Pop!_OS 21.04 :(
