### ISSUE TITLE
Double update / delay

### ISSUE THREAD

**Issue by RickDW** [pop-os/shell#547]
Hi all, 
I've noticed that when a windows gets moved around or the order gets switched, or more generally whenever the layout of multiple windows is affected, that the repositioning and resizing of the non-focused windows happens after the repositioning and resizing of the focused window on which the action was performed. Basically it causes a bit of a stutter is what it feels like. Although it's not a huge issue for me, it does make the whole tiling system feel a lot less smooth and kind of distracting. I've turned off animations in gnome tweaks hoping that would solve it, but all it does is make the double update finish a little faster. 

Would it be possible to get layout updates done in one single update?

**Comment by mmstick** [comment]
Yeah there's a lot of potential for optimization. The focus today is getting things right before making it fast.

**Comment by RickDW** [comment]
Alright, it's good to know it'll get fixed somewhere down the line

**Comment by GeneralPoxter** [comment]
I'm not sure whether this is related, so can @RickDW confirm that I can reproduce?
https://github.com/pop-os/shell/issues/547
I included a more detailed description in the description of the video.

**Comment by RickDW** [comment]
I'm not entirely sure because the animation is slowed down, it kind of does look like my problem but also doesn't. Could you maybe upload a version at normal speed?

**Comment by GeneralPoxter** [comment]
For some reason, it's more noticeable today even at normal speed, so here's the recording:
https://vimeo.com/459377791

**Comment by RickDW** [comment]
Yeah that's easier to see, and I can see you're having the same problem I do. I hadn't noticed the stuttering / bouncing in place, but I get the exact same results when I start gnome tweaks from the terminal. I have no clue how pop shell works under the hood, but I wouldn't be surprised if the problems are connected somehow.

**Comment by GeneralPoxter** [comment]
Okay, hopefully they can find a fix to this soon.

**Comment by jmmaranan** [comment]
Hi @GeneralPoxter @RickDW - do you run pop-shell from source? If you do, I added a Pull Request for this https://github.com/pop-os/shell/pull/555 - maybe you can try it out?

**Comment by GeneralPoxter** [comment]
@jmmaranan, the animations are definitely smoother, but the double animation (e.g. going back to the center of the screen) when opening applications still persists.
I installed directly from https://github.com/jmmaranan/shell/tree/stutter-fix, but while running `sh rebuild.sh`, the `make install`, some errors appeared in the log:
```
Could not create transient scope for PID 20625: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 20625 does not exist.
Could not create transient scope for PID 20638: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 20638 does not exist.
Could not create transient scope for PID 20641: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 20641 does not exist.
GNOME Shell started at Mon Sep 21 2020 12:38:55 GMT-0400 (Eastern Daylight Time)
Registering session with GDM
Error registering session with GDM: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.DisplayManager was not provided by any .service files
pop-shell:  [INFO]

 Fork(0,0) [0,32,2560,1408]: {
    workspace: (1),
    left:  Window(3,0) (Rect(0,32,2560,1408)),
  }

pop-shell:  [INFO]

 Fork(0,0) [0,32,2560,1408]: {
    workspace: (1),
    left:  Window(3,0) (Rect(0,32,2560,1408)),
  }
 Fork(1,0) [0,32,2560,1408]: {
    workspace: (0),
    left:  Window(1,0) (Rect(16,48,1256,1376)),
  }

pop-shell:  [INFO]

 Fork(0,0) [0,32,2560,1408]: {
    workspace: (1),
    left:  Window(3,0) (Rect(0,32,2560,1408)),
  }
 Fork(1,0) [16,48,2528,1376]: {
    workspace: (0),
    left:  Window(1,0) (Rect(16,48,1256,1376)),
    right: Window(2,0) (Rect(1288,48,1256,680)),
  }

pop-shell:  [INFO]

 Fork(0,0) [0,32,2560,1408]: {
    workspace: (1),
    left:  Window(3,0) (Rect(0,32,2560,1408)),
  }
 Fork(1,0) [16,48,2528,1376]: {
    workspace: (0),
    left:  Fork(2,0) [16,48,1256,1376]: {
      workspace: (0),
      left:  Window(1,0) (Rect(16,48,1256,1376)),
      right: Window(0,0) (Rect(1288,744,1256,680)),
    },
    right: Window(2,0) (Rect(1288,48,1256,680)),
  }
```
The command hangs here, so I had to abort make install in order to return to the command line.
Besides this, pop-shell seems to have installed properly as everything else appears to work fine.

**Comment by jmmaranan** [comment]
The rebuild.sh starts listening to the logs automatically. It is expected. And it will not close until you do CTRL + C.

**Comment by jmmaranan** [comment]
Gnome tweaks and gnome terminal always start in the center when opened. I do not think we can do anything about it. And then shell takes over.

**Comment by GeneralPoxter** [comment]
The problem is not that the window opens in the center though, it's that the window's movement to its tile is being animated twice in rapid succession.

**Comment by jmmaranan** [comment]
I'll look into it again sometime today or this week.

**Comment by jmmaranan** [comment]
@GeneralPoxter - I had pushed another change to the same branch. The tweener is a little bit slower but the effect is a much smoother experience IMO.

**Comment by GeneralPoxter** [comment]
@jmmaranan Still stutters and repeats : (

**Comment by jmmaranan** [comment]
@GeneralPoxter - you are probably not using the latest commit from here: https://github.com/jmmaranan/shell/commit/686f19eea5d8b181fd58c26ff885b27fe95fe514 - it is not faster, it is a bit slower. I'll post later on how the animation looks.

**Comment by GeneralPoxter** [comment]
@jmmaranan Sorry I pulled from the wrong branch.
It's definitely smoother this time, and the slow animations seem to get rid of most of the "flashing back" when the windows are opened.
On occasion, this still does occur, but it disappears if I increase the duration to 300.

**Comment by jmmaranan** [comment]
@GeneralPoxter - the implementation has trade offs UX and techwise. However, need to check with @mmstick - why the tweener is set to 149ms. If users would prefer different one, a candidate to add prefs.js. Users also has different hardware, it might be OK on others  at 275ms on the PR or not.

**Comment by GeneralPoxter** [comment]
@jmmaranan By implementation, do you mean giving users an option to turn off window placement animations?

**Comment by jmmaranan** [comment]
@GeneralPoxter - I was referring to the PR. And additional changes that need to come with it. Since it works fine for me on 275ms, you said it worked for you at 300ms, then need to supply way to change it, and adjust the delay as necessary or completely turn it off.

**Comment by RickDW** [comment]
Haven't tried out your implementation yet, hope to get around to it this week. But turning off window placement animations would be a nice small feature to have! I like having most of my system looking smooth but personally the window placement animations are a little bit much.

**Comment by GeneralPoxter** [comment]
@jmmaranan Yes turning off gnome animations is not the optimal choice because
1) It doesn't prevent the window from flashing in the center before tiling into position
2) It removes all other non-window tiling related animations
I agree with RickDW. I think an option to turn off window tiling animations and just show the window where it's supposed to go would be the optimal solution.

**Comment by jmmaranan** [comment]
Will investigate more. But basically some windows would be gnome controlled when they open somewhere. Tweaks always in center. As is Terminal.

I'll send a patch for adding the option to turn off/on the tweener. Or update the delay with values from 150ms to 1s

**Comment by mmstick** [comment]
Basically, there's no way to control where a window initially appears. GNOME Shell tells us when a new window has been mapped and the first frame is drawn, and only then can we control where it's placed. So the flash you see is just the window being drawn, and then Pop Shell registering and placing it.

**Comment by jmmaranan** [comment]
@mmstick - the double positioning happens because of the tweener or the tweener's values are not optimized. Since it is subjective, I would send a PR to have a pref.js entry for adjusting the delay/timeout from 150ms to 500ms. Greater than 500ms does not seem to be a good experience. And then as requested by folks in this thread. An option to not tween the windows altogether.

I see the double positioning in the stacking windows branch more often for mouse users. So I would think many folks would complain. But a nice to have on the stacking branch.

**Comment by GeneralPoxter** [comment]
I tested stutter-fix as of commit 073790f3effdf16ed32e0784e32eb095e43f442b, and it seems to work significantly better and smoother. I no longer produce as severe stuttering as before.

**Comment by jmmaranan** [comment]
I will have to postpone the changes for this in favor of working on some updates to prefs.js

**Comment by GeneralPoxter** [comment]
Okay. I'm not sure exactly what changed between the last time I tried it and this time, but I haven't encountered any stuttering so far in the last 2 days!

**Comment by mmstick** [comment]
We released the stacking feature on Friday, which may have fixed it.

**Comment by jmmaranan** [comment]
@GeneralPoxter, you might still have the fix from my branch on your local. You can do `make uninstall` and ALT+F2 then r to restart the shell.

**Comment by jmmaranan** [comment]
It is still there, but not too noticeable.

**Comment by GeneralPoxter** [comment]
@jmmaranan I'm not sure what you want me to do. I was just saying that the stutter-fix as of commit 073790f3effdf16ed32e0784e32eb095e43f442b has been working for the last two days. I checked that that's the branch I have installed. Well on occassion, there is a stutter/double animation, but like you said, it's barely noticeable and not as annoying as it was before.

**Comment by jmmaranan** [comment]
@GeneralPoxter - I was pertaining to the `master_focal` changes, the issue is still there but not too noticeable. You might want to try master.

**Comment by GeneralPoxter** [comment]
@jmmaranan I gave it a go with the latest commit of `master_focal`, but the problem there is significantly worse for me. I can visually detect the window moving to its tiling position, then moving back to its starting position, and then moving to its tiling position as seen in the original screen recordings. In this case, I would say the double animation is even more noticeable than some of the previous fixes made in `stutter-fix`.

**Comment by jmmaranan** [comment]
@GeneralPoxter - ok - thanks for trying. I will try to update stutter-fix with changes from master from time to time so you are not missing out. Once I can get the GUI for the options to this, you can safely edit as much as you like from Tweaks.

**Comment by GeneralPoxter** [comment]
@jmmaranan thanks!

**Comment by jmmaranan** [comment]
@GeneralPoxter - I pushed some changes to `stutter-fix` branch. Please try it out, I might have the chance to merge this much earlier if it works out for you.

**Comment by GeneralPoxter** [comment]
@jmmaranan There is occasional stuttering in the new commit, and I believe it occurs more frequently than before probably due to the faster duration speeds.

**Comment by jmmaranan** [comment]
I had put it back to 275ms. Will update this thread once I get the prefs update going.

**Comment by mmstick** [comment]
Is this still an issue?

**Comment by jmmaranan** [comment]
@mmstick - yes it is - I am working on something to address this.

**Comment by jmmaranan** [comment]
There seems to be two parts to this, the flicker and then the option to completely turn it off.

**Comment by GeneralPoxter** [comment]
@mmstick, though jmmaranan's fixes have drastically improved quality-of-life when opening windows in pop shell, the flicker still does occur on occasion, as of the latest commit in jmmaranan's stutter-fix branch.

**Comment by jmmaranan** [comment]
@GeneralPoxter - can you try this one? It should now be much buttery smooth than before.  The new compile commands are:
```bash
make debug # for development
make local-install # for source install
```

https://github.com/jmmaranan/shell/tree/flicker_focal

**Comment by GeneralPoxter** [comment]
@jmmaranan It is definitely much smoother, faster, and more consistent than before, but still (probably somewhere around once every 20 window openings or so) a flicker occurs.

**Comment by jmmaranan** [comment]
Sure, I will look into those number of windows.

Do you mind posting your monitor setup? I would wonder if folks would have 20 windows opened at a given time in a single monitor or would that be spread across multiple workspaces. Or stacks. Or some mixed minimized and shown?

Just looking from a different perspective. Or factoring in graphics and cpu workload.

**Comment by jmmaranan** [comment]
@GeneralPoxter - I am not able to reproduce the flicker issue anymore, but I did notice that the latest window being opened (Pop Shop) would slowly try to slide/fit into the rest of the group. But no windows go back to their starting position under these number of opened windows. 

I would defer this to System76 if we would still need adjustments on #618, 20 ms Tween observer might be too much given JS. But I think the behavior is much better than what is in master.

![image](https://user-images.githubusercontent.com/348125/95472161-b3974100-0950-11eb-9885-50a451f3e657.png)
