### ISSUE TITLE
Moving application from one single-application workspace to another

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#77]
**Steps to reproduce**:

1. Open up an app 1 workspace
2. Open another app on 2nd workspace
3. From the Activities Overview, drag the app from 1 workspace to the second one. 

**Expected behaviour**:

Apps divide the workspace in 2.

**Actual behaviour**:

Both apps take the full width of the screen.

*Note*: This seems to work fine with keyboard shortcuts, so it seems like there's a specific problem doing it with the cursor.

**Comment by leviport** [comment]
I have intermittently seen this as well. I have also seen one that seems related, so I'll put it here as well:

If I open two windows on a workspace in tiling mode, and the screen is bisected appropriately, I can use <kbd>Super</kbd> + <kbd>Shift</kbd> + Up/Down to move one to another workspace. When I move one to an empty workspace below, the window remains at 1/2 screen size, and so does the one it used to be next to, even though both windows are now on their own workspaces and should take up the whole screen. Here are some screenshots of what I mean:

Two windows on one workspace:
![Screenshot from 2020-03-16 07-53-53](https://user-images.githubusercontent.com/13512097/76765076-76245980-675b-11ea-9bc4-fc684d44464e.png)

Then I use <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>Down</kbd> to move my terminal down to an empty workspace below:
![Screenshot from 2020-03-16 07-53-58](https://user-images.githubusercontent.com/13512097/76765160-93f1be80-675b-11ea-8f84-ff13a57950c6.png)

and both gnome-terminal and Emacs remain at half size on their own workspaces:
![Screenshot from 2020-03-16 07-54-01](https://user-images.githubusercontent.com/13512097/76765222-a966e880-675b-11ea-9cc4-af2f725bc228.png)

**Comment by mmstick** [comment]
I wonder when this started happening

**Comment by leviport** [comment]
I didn't notice it Friday, but it was happening this morning before I pulled & rebuilt so it was probably happening then. It is still happening after my most recent pull & rebuild.

**Comment by leviport** [comment]
It looks like this one has been solved now, and I can't reproduce it. We can reopen if I'm incorrect or it re-emerges.

**Comment by nicolae-stroncea** [comment]
I'm on the latest commit(0c480fb8c0f0c39a5842cff89f38d807600c2a14) and issue still occurs

**Comment by leviport** [comment]
Hmm, I'm on the same and it's definitely not happening to me anymore. I'll reopen it just in case though.

**Comment by mmstick** [comment]
Closing issues that can't be replicated anymore

**Comment by nicolae-stroncea** [comment]
i'm on latest commit(cf121b32c1bb5bfb37f38d0bd876d29be98185ba), and it's still popping up occasionally. This is the stack trace for when I move a window from 1st workspace to 2nd:

```
UUID is "pop-shell@system76.com"
journalctl -o cat -n 0 -f "$(which gnome-shell)" | grep -v warning
hiding active hint
Usage of object.actor is deprecated for Panel
get@resource:///org/gnome/shell/ui/environment.js:285:29
setStyle@/home/nicolae/.local/share/gnome-shell/extensions/TransparentTopbar@enrico.sorio.net/extension.js:7:5
enable/<@/home/nicolae/.local/share/gnome-shell/extensions/TransparentTopbar@enrico.sorio.net/extension.js:21:9
actionMoveWindow@resource:///org/gnome/shell/ui/windowManager.js:2174:23
_showWorkspaceSwitcher@resource:///org/gnome/shell/ui/windowManager.js:2132:18

Usage of object.actor is deprecated for Panel
get@resource:///org/gnome/shell/ui/environment.js:285:29
setStyle@/home/nicolae/.local/share/gnome-shell/extensions/TransparentTopbar@enrico.sorio.net/extension.js:8:5
enable/<@/home/nicolae/.local/share/gnome-shell/extensions/TransparentTopbar@enrico.sorio.net/extension.js:21:9
actionMoveWindow@resource:///org/gnome/shell/ui/windowManager.js:2174:23
_showWorkspaceSwitcher@resource:///org/gnome/shell/ui/windowManager.js:2132:18

pop-shell:  [INFO] workspace 2 was removed
pop-shell:  [INFO] showing overview
hiding active hint
pop-shell:  [INFO] showing overview
hiding active hint
hiding active hint
Usage of object.actor is deprecated for Panel
get@resource:///org/gnome/shell/ui/environment.js:285:29
setStyle@/home/nicolae/.local/share/gnome-shell/extensions/TransparentTopbar@enrico.sorio.net/extension.js:7:5
enable/<@/home/nicolae/.local/share/gnome-shell/extensions/TransparentTopbar@enrico.sorio.net/extension.js:21:9
actionMoveWindow@resource:///org/gnome/shell/ui/windowManager.js:2174:23
_showWorkspaceSwitcher@resource:///org/gnome/shell/ui/windowManager.js:2132:18

Usage of object.actor is deprecated for Panel
get@resource:///org/gnome/shell/ui/environment.js:285:29
setStyle@/home/nicolae/.local/share/gnome-shell/extensions/TransparentTopbar@enrico.sorio.net/extension.js:8:5
enable/<@/home/nicolae/.local/share/gnome-shell/extensions/TransparentTopbar@enrico.sorio.net/extension.js:21:9
actionMoveWindow@resource:///org/gnome/shell/ui/windowManager.js:2174:23

```

The interesting thing that happens is that the moment I move the window around, it moves back to its original workspace.

**Comment by mmstick** [comment]
Those are from a different extension: `TransparentTopbar@enrico.sorio.net`
