### ISSUE TITLE
plugin closes all windows when unlock the screen

### ISSUE THREAD

**Issue by charafau** [pop-os/shell#97]
Like in title, when you lock the screen and unlock it, plugin will fail and close all previously opened windows.

**Comment by mmstick** [comment]
I haven't seen the closing window behavior, but GNOME is disabling the extension when locking the screen

**Comment by mmstick** [comment]
This should be fixed in 86baa2a9e4f7d32c87e12974dd257a3c89ba4eba

**Comment by charafau** [comment]
It still occurs for me. My system:

arch linux, gnome 3.36 and wayland (I suspect this)
